import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";

import categoryDisplayMap from "./categoryMap.js";
import { techCategoryMap } from "./langToCat.js";
import { getLearningMeta } from "./learningMeta.js";

/* ==========================================================
                    DEVDNA PDF REPORT ENGINE
   ========================================================== */

const PAGE = {
  width: 210,
  height: 297,
  margin: 16,
  contentWidth: 178,
};

const SPACE = {
  xs: 3,
  sm: 6,
  md: 10,
  lg: 16,
  xl: 22,
  xxl: 30,
};

const FONT = {
  hero: 28,
  h1: 22,
  h2: 17,
  h3: 14,
  body: 11,
  small: 9,
  tiny: 8,
};

const COLORS = {
  primary: "#2563EB",
  primaryLight: "#DBEAFE",

  secondary: "#1E293B",

  success: "#16A34A",
  warning: "#F59E0B",
  danger: "#DC2626",

  text: "#111827",
  muted: "#6B7280",

  white: "#FFFFFF",

  border: "#E5E7EB",

  card: "#F8FAFC",

  background: "#FFFFFF",

  progressBg: "#E5E7EB",

  high: "#EF4444",
  medium: "#F59E0B",
  low: "#10B981",
};

/* ==========================================================
                        PDF STATE
   ========================================================== */

const pdf = {
  doc: null,

  cursorY: PAGE.margin,

  currentPage: 1,

  username: "",

  reportDate: "",

  data: null,
};

/* ==========================================================
                    INITIALIZATION
   ========================================================== */

function initPDF(data, username) {
  pdf.doc = new jsPDF({
    orientation: "portrait",
    unit: "mm",
    format: "a4",
  });

  pdf.cursorY = PAGE.margin;

  pdf.currentPage = 1;

  pdf.username = username;

  pdf.reportDate = new Date().toLocaleDateString();

  pdf.data = data;
}

/* ==========================================================
                    TYPOGRAPHY ENGINE
   ========================================================== */

function font(
  size = FONT.body,
  weight = "normal",
  color = COLORS.text
) {
  pdf.doc.setFont("helvetica", weight);

  pdf.doc.setFontSize(size);

  pdf.doc.setTextColor(color);
}

/* ==========================================================
                    PAGE MANAGEMENT
   ========================================================== */

function newPage() {
  pdf.doc.addPage();

  pdf.currentPage++;

  pdf.cursorY = PAGE.margin;

  drawHeader();

  drawFooter();
}

function ensureSpace(requiredHeight = 20) {
  if (
    pdf.cursorY + requiredHeight >
    PAGE.height - PAGE.margin
  ) {
    newPage();
  }
}

function moveY(amount) {
  ensureSpace(amount);

  pdf.cursorY += amount;
}

/* ==========================================================
                    HEADER
   ========================================================== */

function drawHeader() {
  pdf.doc.setFillColor(COLORS.primary);

  pdf.doc.rect(
    0,
    0,
    PAGE.width,
    12,
    "F"
  );

  font(
    FONT.small,
    "bold",
    COLORS.white
  );

  pdf.doc.text(
    "DevDNA • Developer Intelligence Report",
    PAGE.margin,
    8
  );
}

/* ==========================================================
                    FOOTER
   ========================================================== */

function drawFooter() {
  const y = PAGE.height - 8;

  pdf.doc.setDrawColor(COLORS.border);

  pdf.doc.line(
    PAGE.margin,
    y - 3,
    PAGE.width - PAGE.margin,
    y - 3
  );

  font(
    FONT.tiny,
    "normal",
    COLORS.muted
  );

  pdf.doc.text(
    "Generated by DevDNA",
    PAGE.margin,
    y
  );

  pdf.doc.text(
    pdf.reportDate,
    PAGE.width / 2,
    y,
    {
      align: "center",
    }
  );

  pdf.doc.text(
    `Page ${pdf.currentPage}`,
    PAGE.width - PAGE.margin,
    y,
    {
      align: "right",
    }
  );
}

/* ==========================================================
                BASIC DRAWING HELPERS
   ========================================================== */

function line(x1, y1, x2, y2) {
  pdf.doc.line(x1, y1, x2, y2);
}

function roundedBox(
  x,
  y,
  w,
  h,
  fill = COLORS.card
) {
  pdf.doc.setFillColor(fill);

  pdf.doc.setDrawColor(COLORS.border);

  pdf.doc.roundedRect(
    x,
    y,
    w,
    h,
    3,
    3,
    "FD"
  );
}

/* ==========================================================
                    TEXT HELPERS
   ========================================================== */

function centerText(
  text,
  y,
  size = FONT.h2,
  color = COLORS.text
) {
  font(size, "bold", color);

  pdf.doc.text(
    text,
    PAGE.width / 2,
    y,
    {
      align: "center",
    }
  );
}

function leftText(
  text,
  x,
  y,
  size = FONT.body,
  weight = "normal",
  color = COLORS.text,
  maxWidth = null
) {
  font(size, weight, color);

  if (maxWidth) {
    pdf.doc.text(text, x, y, { maxWidth });
  } else {
    pdf.doc.text(text, x, y);
  }
}

function rightText(
  text,
  x,
  y,
  size = FONT.body,
  weight = "normal",
  color = COLORS.text
) {
  font(size, weight, color);

  pdf.doc.text(text, x, y, {
    align: "right",
  });
}

function paragraph(
  text,
  x,
  width,
  lineHeight = 5
) {
  font();

  const lines =
    pdf.doc.splitTextToSize(
      text,
      width
    );

  pdf.doc.text(
    lines,
    x,
    pdf.cursorY
  );

  moveY(lines.length * lineHeight);
}

/* ==========================================================
                    SECTION TITLE
   ========================================================== */

function section(title) {
  ensureSpace(16);

  roundedBox(
    PAGE.margin,
    pdf.cursorY,
    PAGE.contentWidth,
    10,
    COLORS.primaryLight
  );

  leftText(
    title,
    PAGE.margin + 5,
    pdf.cursorY + 6.5,
    FONT.h3,
    "bold",
    COLORS.secondary
  );

  moveY(16);
}

/* ==========================================================
                    STAT CARD
========================================================== */

function drawStatCard({
  x,
  y,
  width = 40,
  height = 26,
  title,
  value,
  color = COLORS.primary,
}) {
  roundedBox(x, y, width, height);

  pdf.doc.setFillColor(color);

  pdf.doc.roundedRect(
    x,
    y,
    width,
    5,
    3,
    3,
    "F"
  );

  leftText(
    title,
    x + 4,
    y + 11,
    FONT.small,
    "bold",
    COLORS.muted
  );

  leftText(
    String(value),
    x + 4,
    y + 20,
    FONT.h2,
    "bold",
    COLORS.secondary
  );
}

/* ==========================================================
                METRIC GRID
========================================================== */

function drawMetricGrid(cards = []) {

  const gap = 6;

  const width = (PAGE.contentWidth - gap) / 2;

  const height = 26;

  const startY = pdf.cursorY;

  cards.forEach((card, index) => {

    const row = Math.floor(index / 2);

    const col = index % 2;

    drawStatCard({

      ...card,

      x: PAGE.margin + col * (width + gap),

      y: startY + row * (height + gap),

      width,

      height

    });

  });

  const rows = Math.ceil(cards.length / 2);

  pdf.cursorY = startY + rows * (height + gap);

}

/* ==========================================================
                PROGRESS BAR
========================================================== */

function drawProgressBar({
  x,
  y,
  width = 100,
  percent = 0,
  color = COLORS.primary,
}) {
  pdf.doc.setFillColor(COLORS.progressBg);

  pdf.doc.roundedRect(
    x,
    y,
    width,
    5,
    2,
    2,
    "F"
  );

  pdf.doc.setFillColor(color);

  pdf.doc.roundedRect(
    x,
    y,
    width * (percent / 100),
    5,
    2,
    2,
    "F"
  );
}

/* ==========================================================
                ROLE BAR
========================================================== */

function drawRoleBar(role, score) {
  ensureSpace(12);

  leftText(
    categoryDisplayMap[role] || role,
    PAGE.margin,
    pdf.cursorY + 2,
    FONT.body,
    "bold"
  );

  rightText(
    `${score.toFixed(1)}%`,
    PAGE.width - PAGE.margin,
    pdf.cursorY + 2,
    FONT.body,
    "bold"
  );

  drawProgressBar({
    x: PAGE.margin,

    y: pdf.cursorY + 5,

    width: PAGE.contentWidth,

    percent: score,
  });

  moveY(12);
}

/* ==========================================================
                LANGUAGE BAR
========================================================== */

function drawLanguageBar(language, percent) {
  ensureSpace(11);

  leftText(
    language,
    PAGE.margin,
    pdf.cursorY + 2,
    FONT.body,
    "bold"
  );

  rightText(
    `${percent.toFixed(1)}%`,
    PAGE.width - PAGE.margin,
    pdf.cursorY + 2,
    FONT.body,
    "bold"
  );

  drawProgressBar({
    x: PAGE.margin,

    y: pdf.cursorY + 5,

    width: PAGE.contentWidth,

    percent,
    color: COLORS.success,
  });

  moveY(11);
}

/* ==========================================================
                BADGE HELPERS
========================================================== */

function getBadgeWidth(text) {
  pdf.doc.setFontSize(FONT.tiny);
  return pdf.doc.getTextWidth(text) + 8;
}

/* ==========================================================
                    BADGE
========================================================== */

function drawBadge({
  text,
  x,
  y,
  bg,
  color = COLORS.white,
}) {
  font(FONT.tiny, "bold", color);

  const width =
    pdf.doc.getTextWidth(text) + 8;

  pdf.doc.setFillColor(bg);

  pdf.doc.roundedRect(
    x,
    y,
    width,
    6,
    2,
    2,
    "F"
  );

  pdf.doc.text(
    text,
    x + 4,
    y + 4.2
  );
}

/* ==========================================================
            PRIORITY BADGE
========================================================== */

function drawPriorityBadge(
  priority,
  x,
  y
) {
  let color = COLORS.medium;

  if (priority === "High")
    color = COLORS.high;

  if (priority === "Low")
    color = COLORS.low;

  drawBadge({
    text: priority,

    x,

    y,

    bg: color,
  });
}

/* ==========================================================
            DIFFICULTY BADGE
========================================================== */

function drawDifficultyBadge(
  difficulty,
  x,
  y
) {
  let color = COLORS.medium;

  if (difficulty === "Easy")
    color = COLORS.low;

  if (difficulty === "Advanced")
    color = COLORS.high;

  drawBadge({
    text: difficulty,

    x,

    y,

    bg: color,
  });
}

/* ==========================================================
                KEY VALUE
========================================================== */

function drawKeyValue(
  key,
  value
) {
  ensureSpace(8);

  leftText(
    key,
    PAGE.margin,
    pdf.cursorY,
    FONT.body,
    "bold"
  );

  rightText(
    String(value),
    PAGE.width - PAGE.margin,
    pdf.cursorY
  );

  moveY(8);
}

/* ==========================================================
                DIVIDER
========================================================== */

function divider() {
  pdf.doc.setDrawColor(
    COLORS.border
  );

  pdf.doc.line(
    PAGE.margin,
    pdf.cursorY,
    PAGE.width - PAGE.margin,
    pdf.cursorY
  );

  moveY(5);
}

/* ==========================================================
            TECHNOLOGY CHIP
========================================================== */

function drawTechChip(
  tech,
  x,
  y
) {
  font(
    FONT.tiny,
    "bold",
    COLORS.secondary
  );

  const width =
    pdf.doc.getTextWidth(tech) + 10;

  pdf.doc.setFillColor(
    COLORS.primaryLight
  );

  pdf.doc.roundedRect(
    x,
    y,
    width,
    7,
    2,
    2,
    "F"
  );

  pdf.doc.text(
    tech,
    x + 5,
    y + 4.7
  );

  return width;
}

/* ==========================================================
                TABLE
========================================================== */

function drawTable({
  head,
  body,
}) {
  autoTable(pdf.doc, {
    head,

    body,

    startY: pdf.cursorY,

    margin: {
      left: PAGE.margin,
      right: PAGE.margin,
    },

    styles: {
      fontSize: 9,

      cellPadding: 2,
    },

    headStyles: {
      fillColor: [37, 99, 235],

      textColor: 255,
    },

    alternateRowStyles: {
      fillColor: [248, 250, 252],
    },
  });

  pdf.cursorY =
    pdf.doc.lastAutoTable.finalY + 10;
}

/* ==========================================================
            RESPONSE 1B ENDS HERE
========================================================== */

/* ==========================================================
                    COVER PAGE
========================================================== */

function getBestRole(skillScores = {}) {
  const sorted = Object.entries(skillScores).sort(
    (a, b) => b[1] - a[1]
  );

  if (!sorted.length) return "Unknown";

  return categoryDisplayMap[sorted[0][0]] || sorted[0][0];
}

function drawHeroBackground() {
  pdf.doc.setFillColor(COLORS.primary);

  pdf.doc.rect(
    0,
    0,
    PAGE.width,
    55,
    "F"
  );

  pdf.doc.setFillColor(255, 255, 255);

  pdf.doc.circle(
    190,
    15,
    25,
    "F"
  );

  pdf.doc.setFillColor(COLORS.primaryLight);

  pdf.doc.circle(
    185,
    10,
    20,
    "F"
  );
}

function drawCoverInfoCard() {

  const x = PAGE.margin;

  const y = 95;

  const w = PAGE.contentWidth;

  const h = 70;

  roundedBox(
    x,
    y,
    w,
    h,
    "#FFFFFF"
  );

  drawKeyValue(
    "Developer",
    pdf.username
  );

  drawKeyValue(
    "Primary Role",
    getBestRole(
      pdf.data.skillScores
    )
  );

  drawKeyValue(
    "Repositories",
    pdf.data.totalRepos
  );

  drawKeyValue(
    "Languages",
    Object.keys(
      pdf.data.langPercentages
    ).length
  );

  drawKeyValue(
    "Known Technologies",
    pdf.data.knownTech.length
  );

  drawKeyValue(
    "Generated",
    pdf.reportDate
  );

}

function drawCoverHighlights() {

  moveY(10);

  section("Highlights");

  const cards = [
    {
      title: "Top Role",
      value: getBestRole(pdf.data.skillScores),
      color: COLORS.primary
    },

    {
      title: "Repositories",
      value: pdf.data.totalRepos,
      color: COLORS.success
    },

    {
      title: "Average Stars",
      value: Math.round(pdf.data.averageStars),
      color: COLORS.warning
    },

    {
      title: "Popular Project",
      value: pdf.data.popularProject,
      color: COLORS.primary
    }
  ];

  drawMetricGrid(cards);

}

function drawCoverPage() {

  pdf.cursorY = PAGE.margin;

  drawHeroBackground();

  centerText(
    "DevDNA",
    26,
    FONT.hero,
    COLORS.white
  );

  centerText(
    "Developer Intelligence Report",
    36,
    FONT.h3,
    COLORS.white
  );

  font(
    FONT.body,
    "normal",
    COLORS.white
  );

  pdf.doc.text(
    "GitHub Profile Analysis",
    PAGE.width / 2,
    46,
    {
      align: "center"
    }
  );

  pdf.cursorY = 108;

  drawCoverInfoCard();

  pdf.cursorY = 180;

  drawCoverHighlights();

  pdf.doc.setDrawColor(
    COLORS.border
  );

  pdf.doc.line(
    PAGE.margin,
    PAGE.height - 28,
    PAGE.width - PAGE.margin,
    PAGE.height - 28
  );

  font(
    FONT.small,
    "italic",
    COLORS.muted
  );

  pdf.doc.text(
    "Generated automatically from public GitHub repositories and repository metadata.",
    PAGE.width / 2,
    PAGE.height - 20,
    {
      align: "center",
      maxWidth: 170
    }
  );

  drawFooter();

  newPage();

}

/* ==========================================================
                RESPONSE 2A ENDS HERE
========================================================== */

/* ==========================================================
                EXECUTIVE SUMMARY
========================================================== */

function drawExecutiveSummary() {

  section("Executive Summary");

  const bestRole = getBestRole(pdf.data.skillScores);

  const totalLanguages =
    Object.keys(pdf.data.langPercentages || {}).length;

  const summary =
    `${pdf.username} owns ${pdf.data.totalRepos} public repositories and demonstrates strongest alignment with the ${bestRole} role. The profile spans ${totalLanguages} programming languages and ${pdf.data.knownTech.length} recognized technologies.`;

  paragraph(
    summary,
    PAGE.margin,
    PAGE.contentWidth
  );

  moveY(6);

}

/* ==========================================================
                PROFILE METRICS
========================================================== */

function drawProfileMetrics() {

  section("Profile Metrics");

  const cards = [

    {
      title: "Repositories",
      value: pdf.data.totalRepos,
      color: COLORS.primary
    },

    {
      title: "Known Tech",
      value: pdf.data.knownTech.length,
      color: COLORS.success
    },

    {
      title: "Languages",
      value: Object.keys(
        pdf.data.langPercentages || {}
      ).length,
      color: COLORS.warning
    },

    {
      title: "Average Stars",
      value: Math.round(
        pdf.data.averageStars || 0
      ),
      color: COLORS.primary
    },

    {
      title: "Forks",
      value: pdf.data.totalForks || 0,
      color: COLORS.success
    },

    {
      title: "Repositories With Description",
      value: pdf.data.withDesc || 0,
      color: COLORS.warning
    },

    {
      title: "Collaborative Projects",
      value: pdf.data.collabedProjects || 0,
      color: COLORS.warning
    }

  ];

  drawMetricGrid(cards);

}

/* ==========================================================
                STRENGTH INDICATORS
========================================================== */

function drawStrengthIndicators() {

  section("Strength Indicators");

  const strengths = [];

  if (pdf.data.totalRepos >= 20)
    strengths.push("Strong technological exposure");

  if (pdf.data.knownTech.length >= 15)
    strengths.push("Broad technological exposure");

  if (
    Object.keys(
      pdf.data.langPercentages || {}
    ).length >= 4
  )
    strengths.push("Good language diversity");

  if (pdf.data.averageStars >= 100)
    strengths.push("Projects receive community attention");

  if (!strengths.length)
    strengths.push(
      "Early stage developer with good growth potential."
    );

  for (const strength of pdf.data.strengths) {
    strengths.push(strength);
  }

  strengths.forEach((item, index) => {

    ensureSpace(8);

    leftText(
      `• ${item}`,
      PAGE.margin,
      pdf.cursorY,
      FONT.body
    );

    moveY(8);

  });

}


function drawIntermediatesIndicators() {

  section("Intermediate Indicators");

  const intermediates = [];

  for (const intermediate of pdf.data.intermediates) {
    intermediates.push(intermediate);
  }

  intermediates.forEach((item, index) => {

    ensureSpace(8);

    leftText(
      `• ${item}`,
      PAGE.margin,
      pdf.cursorY,
      FONT.body
    );

    moveY(8);

  });

}

/* ==========================================================
                TECHNOLOGY PREVIEW
========================================================== */

function drawTechnologyPreview() {

  section("Technology Preview");

  const techs =
    (pdf.data.knownTech || [])
      .slice(0, 20);

  let x = PAGE.margin;
  let y = pdf.cursorY;

  techs.forEach((tech) => {

    const width =
      pdf.doc.getTextWidth(tech) + 10;

    if (
      x + width >
      PAGE.width - PAGE.margin
    ) {
      x = PAGE.margin;
      y += 10;
    }

    drawTechChip(
      tech,
      x,
      y
    );

    x += width + 4;

  });

  pdf.cursorY = y + 15;

}

/* ==========================================================
                EXECUTIVE DASHBOARD
========================================================== */

function drawExecutiveDashboard() {

  drawExecutiveSummary();

  drawProfileMetrics();

  drawStrengthIndicators();

  drawIntermediatesIndicators();

  drawTechnologyPreview();

}

/* ==========================================================
                    ROLE ANALYSIS
========================================================== */

function getSortedRoles() {

  return Object.entries(
    pdf.data.skillScores || {}
  ).sort((a, b) => b[1] - a[1]);

}

/* ==========================================================
                ROLE SCORE TABLE
========================================================== */

function drawRoleScoreTable() {

  section("Role Compatibility");

  const sorted = getSortedRoles();

  sorted.forEach(([role, score]) => {

    drawRoleBar(role, score);

  });

}

/* ==========================================================
                BEST ROLE INSIGHT
========================================================== */

function drawBestRoleInsight() {

  section("Primary Career Match");

  const sorted = getSortedRoles();

  if (!sorted.length) {

    paragraph(
      "No role analysis data available.",
      PAGE.margin,
      PAGE.contentWidth
    );

    return;

  }

  const [role, score] = sorted[0];

  const readable =
    categoryDisplayMap[role] || role;

  let verdict = "";

  if (score >= 75)
    verdict =
      "Your GitHub profile strongly aligns with this role and demonstrates an advanced level of practical exposure .";

  else if (score >= 55)
    verdict =
      "Your profile shows good alignment with this role, although additional projects can further strengthen it .";

  else if (score >= 30)
    verdict =
      "You possess foundational skills for this role but require broader project experience .";

  else
    verdict =
      "This role is currently underrepresented within your GitHub portfolio. Data is not sufficient to provide a verdict .";

  paragraph(
    `Best Matched Role: ${readable} (${score.toFixed(
      1
    )}%)\n\n${verdict}`,
    PAGE.margin,
    PAGE.contentWidth
  );

}

/* ==========================================================
                ROLE STRENGTHS
========================================================== */

function drawRoleStrengths() {

  section("Strongest Areas");

  const sorted = getSortedRoles();

  sorted
    .slice(0, 3)
    .forEach(([role, score], index) => {

      ensureSpace(10);

      leftText(
        `${index + 1}. ${categoryDisplayMap[role] || role}`,
        PAGE.margin,
        pdf.cursorY,
        FONT.body,
        "bold"
      );

      rightText(
        `${score.toFixed(1)}%`,
        PAGE.width - PAGE.margin,
        pdf.cursorY,
        FONT.body,
        "bold",
        COLORS.success
      );

      moveY(8);

    });

}

/* ==========================================================
                IMPROVEMENT AREAS
========================================================== */

function drawImprovementAreas() {

  section("Improvement Opportunities");

  const sorted = getSortedRoles();

  sorted
    .slice(-3)
    .reverse()
    .forEach(([role, score]) => {

      ensureSpace(10);

      leftText(
        categoryDisplayMap[role] || role,
        PAGE.margin,
        pdf.cursorY,
        FONT.body,
        "bold"
      );

      rightText(
        `${score.toFixed(1)}%`,
        PAGE.width - PAGE.margin,
        pdf.cursorY,
        FONT.body,
        "bold",
        COLORS.danger
      );

      moveY(8);

    });

}

function drawGrowthAreas() {

  section("Growth Areas");

  const weaknesses = [];

  for (const weakness of pdf.data.weaknesses) {
    weaknesses.push(weakness);
  }

  weaknesses.forEach((item, index) => {

    ensureSpace(8);

    leftText(
      `• ${item}`,
      PAGE.margin,
      pdf.cursorY,
      FONT.body
    );

    moveY(8);

  });

}

/* ==========================================================
                ROLE SUMMARY
========================================================== */

function drawRoleSummary() {

  section("Role Summary");

  const sorted = getSortedRoles();

  if (!sorted.length) return;

  const topRole =
    categoryDisplayMap[sorted[0][0]] ||
    sorted[0][0];

  const second =
    sorted.length > 1
      ? categoryDisplayMap[sorted[1][0]] ||
      sorted[1][0]
      : "N/A";

  const third =
    sorted.length > 2
      ? categoryDisplayMap[sorted[2][0]] ||
      sorted[2][0]
      : "N/A";

  paragraph(

    `Based on repository metadata, programming language distribution and detected technologies, DevDNA identifies ${topRole} as your strongest career alignment.

Secondary compatibility is observed for ${second}, while ${third} remains another promising direction. These scores should be interpreted as indicators of demonstrated practical experience rather than theoretical knowledge.`,

    PAGE.margin,

    PAGE.contentWidth

  );

}

/* ==========================================================
                COMPLETE ROLE ANALYSIS
========================================================== */

function drawRoleAnalysis() {

  drawRoleScoreTable();

  drawBestRoleInsight();

  drawRoleStrengths();

  drawImprovementAreas();

  drawGrowthAreas();

  drawRoleSummary();

}

/* ==========================================================
                LANGUAGE ANALYSIS
========================================================== */

function getSortedLanguages() {

  return Object.entries(
    pdf.data.langPercentages || {}
  ).sort((a, b) => b[1] - a[1]);

}


/* ==========================================================
                LANGUAGE SUMMARY
========================================================== */

function drawLanguageSummary() {

  section("Language Insights");

  const langs = getSortedLanguages();

  if (!langs.length) return;

  const topLanguage = langs[0][0];
  const topPercent = langs[0][1].toFixed(1);

  let summary =
    `${topLanguage} represents ${topPercent}% of all detected repository code, making it the dominant language in this GitHub profile. `;

  if (langs.length >= 3) {

    summary +=
      `Development activity is distributed across ${langs.length} programming languages, demonstrating exposure to multiple ecosystems while maintaining specialization in ${topLanguage}.`;

  } else {

    summary +=
      `The profile is focused on a relatively small set of programming languages, indicating specialization rather than diversification.`;

  }

  paragraph(
    summary,
    PAGE.margin,
    PAGE.contentWidth
  );

}

/* ==========================================================
                TECHNOLOGY CATEGORY
========================================================== */

function getTechnologyCategories() {

  const categories = {};

  (pdf.data.knownTech || []).forEach((tech) => {

    const category =
      techCategoryMap[tech] || "Other";

    categories[category] =
      (categories[category] || 0) + 1;

  });

  return Object.entries(categories)
    .sort((a, b) => b[1] - a[1]);

}

/* ==========================================================
                CATEGORY TABLE
========================================================== */

function drawTechnologyCategoryTable() {

  section("Technology Categories");

  const body = getTechnologyCategories().map(

    ([category, count]) => [

      category,

      count

    ]

  );

  drawTable({

    head: [[
      "Category",
      "Technologies"
    ]],

    body

  });

}

/* ==========================================================
                CATEGORY INSIGHTS
========================================================== */

function drawCategoryInsights() {

  section("Technology Insights");

  const categories =
    getTechnologyCategories();

  if (!categories.length) return;

  const dominant =
    categories[0][0];

  const count =
    categories[0][1];

  paragraph(

    `Most detected technologies belong to the ${dominant} category (${count} technologies). This indicates that the majority of practical development experience is concentrated within this ecosystem. Diversifying into complementary technology categories can improve overall engineering versatility.`,

    PAGE.margin,

    PAGE.contentWidth

  );

}

/* ==========================================================
                LANGUAGE TABLE
========================================================== */

function drawLanguageTable() {

  section("Language Breakdown");

  const body =
    getSortedLanguages().map(

      ([language, percent]) => [

        language,

        `${percent.toFixed(2)} %`

      ]

    );

  drawTable({

    head: [[
      "Language",
      "Usage"
    ]],

    body

  });

}

/* ==========================================================
                STACK DIVERSITY
========================================================== */

function drawStackDiversity() {

  section("Stack Diversity");

  const totalTech =
    (pdf.data.knownTech || []).length;

  const totalCategories =
    getTechnologyCategories().length;

  drawMetricGrid([

    {
      title: "Technologies",
      value: totalTech,
      color: COLORS.primary
    },

    {
      title: "Categories",
      value: totalCategories,
      color: COLORS.success
    },

    {
      title: "Languages",
      value: Object.keys(
        pdf.data.langPercentages || {}
      ).length,
      color: COLORS.warning
    },

    {
      title: "Top Language",
      value:
        getSortedLanguages()[0]?.[0] || "-",
      color: COLORS.primary
    }

  ]);

}

/* ==========================================================
                COMPLETE LANGUAGE ANALYSIS
========================================================== */

function drawLanguageAnalysis() {

  drawLanguageTable();

  drawLanguageSummary();

  drawStackDiversity();

  drawTechnologyCategoryTable();

  drawCategoryInsights();

}

/* ==========================================================
                    LEARNING ROADMAP
========================================================== */

function getLearningRecommendations() {

  const recommendations = [];

  const knownTech = new Set(
    pdf.data.knownTech || []
  );

  Object.entries(techCategoryMap).forEach(
    ([tech, category]) => {

      if (knownTech.has(tech)) return;

      const meta = getLearningMeta(tech);

      recommendations.push({

        technology: tech,

        category,

        priority: meta.priority,

        difficulty: meta.difficulty,

        duration: meta.duration,

        description: meta.description

      });

    }
  );

  const priorityOrder = {
    High: 0,
    Medium: 1,
    Low: 2
  };

  recommendations.sort((a, b) => {

    const p =
      priorityOrder[a.priority] -
      priorityOrder[b.priority];

    if (p !== 0) return p;

    return a.technology.localeCompare(
      b.technology
    );

  });

  return recommendations;

}

/* ==========================================================
                ROADMAP OVERVIEW
========================================================== */

function drawRoadmapOverview() {

  // Reserve space for:
  // Heading + paragraph + metric grid
  ensureSpace(115);

  section("Learning Roadmap");

  const roadmap =
    getLearningRecommendations();

  paragraph(

    `DevDNA identifies technologies that are currently missing from your GitHub profile and recommends them based on their practical importance, career relevance and ecosystem demand . Higher priority technologies should generally be learned before lower priority ones .
These are just recommendations , learning these depends on your wish .`,

    PAGE.margin,

    PAGE.contentWidth

  );

  moveY(5);

  drawMetricGrid([

    {
      title: "Recommendations",
      value: roadmap.length,
      color: COLORS.primary
    },

    {
      title: "High Priority",
      value:
        roadmap.filter(
          r => r.priority === "High"
        ).length,
      color: COLORS.danger
    },

    {
      title: "Medium",
      value:
        roadmap.filter(
          r => r.priority === "Medium"
        ).length,
      color: COLORS.warning
    },

    {
      title: "Low",
      value:
        roadmap.filter(
          r => r.priority === "Low"
        ).length,
      color: COLORS.success
    }

  ]);

}

/* ==========================================================
                ROADMAP CARDS
========================================================== */

function drawLearningCards(limit = 12) {

  section("Recommended Technologies");

  const roadmap = getLearningRecommendations().slice(0, limit);

  roadmap.forEach(item => {

    ensureSpace(28);

    roundedBox(
      PAGE.margin,
      pdf.cursorY,
      PAGE.contentWidth,
      24
    );

    // Leave space on the right for badges
    leftText(
      item.technology,
      PAGE.margin + 4,
      pdf.cursorY + 7,
      FONT.h3,
      "bold",
      COLORS.text,
      PAGE.contentWidth - 80      // reserve 80px for badges
    );

    const badgeGap = 4;
    const badgeY = pdf.cursorY + 2;

    const difficultyWidth = getBadgeWidth(item.difficulty);
    const priorityWidth = getBadgeWidth(item.priority);

    // Rightmost badge
    const difficultyX =
      PAGE.margin +
      PAGE.contentWidth -
      difficultyWidth -
      4;

    // Badge before it
    const priorityX =
      difficultyX -
      priorityWidth -
      badgeGap;

    drawPriorityBadge(
      item.priority,
      priorityX,
      badgeY
    );

    drawDifficultyBadge(
      item.difficulty,
      difficultyX,
      badgeY
    );

    leftText(
      `Category: ${item.category}`,
      PAGE.margin + 4,
      pdf.cursorY + 15,
      FONT.small,
      "bold",
      COLORS.muted
    );

    pdf.cursorY += 30;

  });

}

/* ==========================================================
                ROADMAP TABLE
========================================================== */

function drawRoadmapTable() {

  section("Roadmap Table");

  const body =
    getLearningRecommendations()
      .map(item => [

        item.technology,

        item.category,

        item.priority,

        item.difficulty,

        item.duration

      ]);

  drawTable({

    head: [[

      "Technology",

      "Category",

      "Priority",

      "Difficulty",

      "Timeline"

    ]],

    body

  });

}

/* ==========================================================
                CATEGORY GAP ANALYSIS
========================================================== */

function drawCategoryGapAnalysis() {

  section("Category Gap Analysis");

  const roadmap =
    getLearningRecommendations();

  const gaps = {};

  roadmap.forEach(item => {

    gaps[item.category] =
      (gaps[item.category] || 0) + 1;

  });

  const body =
    Object.entries(gaps)
      .sort((a, b) => b[1] - a[1])
      .map(([category, count]) => [

        category,

        count

      ]);

  drawTable({

    head: [[
      "Technology Category",
      "Missing Technologies"
    ]],

    body

  });

}

/* ==========================================================
                HIGH PRIORITY SUMMARY
========================================================== */

function drawPrioritySummary() {

  section("Immediate Focus");

  const highPriority =
    getLearningRecommendations()
      .filter(
        item => item.priority === "High"
      )
      .slice(0, 6)
      .map(item => item.technology);

  if (!highPriority.length) {

    paragraph(

      "No immediate learning recommendations available.",

      PAGE.margin,

      PAGE.contentWidth

    );

    return;

  }

  paragraph(

    `Focus first on ${highPriority.join(" , ")}. These technologies have the highest impact on improving your overall developer profile and increasing compatibility with modern software engineering roles.`,

    PAGE.margin,

    PAGE.contentWidth

  );

}

/* ==========================================================
                COMPLETE LEARNING ROADMAP
========================================================== */

function drawLearningRoadmap() {

  drawRoadmapOverview();

  drawLearningCards();

  drawRoadmapTable();

  drawCategoryGapAnalysis();

  drawPrioritySummary();

}

/* ==========================================================
                    FINAL RECOMMENDATIONS
========================================================== */

function drawFinalRecommendations() {

  section("Final Recommendations");

  const recommendations = [];

  const sortedRoles = getSortedRoles();

  if (sortedRoles.length) {

    const topRole =
      categoryDisplayMap[sortedRoles[0][0]] ||
      sortedRoles[0][0];

    recommendations.push(
      `Continue building projects aligned with ${topRole}.`
    );

  }

  if ((pdf.data.totalRepos || 0) < 15) {

    recommendations.push(
      "Increase the number of quality repositories showcasing real-world applications."
    );

  }

  if ((pdf.data.averageStars || 0) < 5) {

    recommendations.push(
      "Publish and share projects to improve visibility and community engagement."
    );

  }

  if (
    Object.keys(pdf.data.langPercentages || {}).length < 3
  ) {

    recommendations.push(
      "Explore additional programming languages to diversify your portfolio."
    );

  }

  if ((pdf.data.knownTech || []).length < 15) {

    recommendations.push(
      "Expand your technology stack by learning modern frameworks and developer tools."
    );

  }

  recommendations.push(
    "Maintain consistent GitHub activity and improve project documentation."
  );

  recommendations.forEach((item) => {

    ensureSpace(8);

    leftText(
      `• ${item}`,
      PAGE.margin,
      pdf.cursorY,
      FONT.body
    );

    moveY(8);

  });

}

/* ==========================================================
                DEVELOPER MATURITY
========================================================== */

function getDeveloperLevel() {

  const repos = pdf.data.totalRepos || 0;

  const tech = (pdf.data.knownTech || []).length;

  const topRole =
    getSortedRoles()[0]?.[1] || 0;

  if (
    repos >= 30 &&
    tech >= 20 &&
    topRole >= 80
  )
    return "Advanced";

  if (
    repos >= 15 &&
    tech >= 12 &&
    topRole >= 60
  )
    return "Intermediate";

  return "Beginner";

}

function drawDeveloperAssessment() {

  section("Developer Assessment");

  const level = getDeveloperLevel();

  let description = "";

  switch (level) {

    case "Advanced":

      description =
        "Your GitHub profile demonstrates strong practical engineering experience with broad technology exposure .";

      break;

    case "Intermediate":

      description =
        "You have a solid technical foundation . Continue building larger production-quality projects .";

      break;

    default:

      description =
        "You are building your portfolio . Focus on consistency, practical projects and learning modern technologies .";

  }

  drawMetricGrid([
    {
      title: "Developer Level",
      value: level,
      color: COLORS.primary
    }
  ]);

  moveY(4);

  paragraph(
    description,
    PAGE.margin,
    PAGE.contentWidth
  );

}

/* ==========================================================
                    REPORT SUMMARY
========================================================== */

function drawReportSummary() {

  section("Report Summary");

  const bestRole = getBestRole(
    pdf.data.skillScores
  );

  paragraph(

    `DevDNA analyzed ${pdf.data.totalRepos} repositories, ${Object.keys(pdf.data.langPercentages || {}).length} programming languages and ${pdf.data.knownTech.length} technologies.

Based on repository metadata and detected skills, your strongest role alignment is ${bestRole}. Continue improving your portfolio through high-quality projects, open-source contributions and consistent GitHub activity.`,

    PAGE.margin,

    PAGE.contentWidth

  );

}

/* ==========================================================
                    CLOSING PAGE
========================================================== */

function drawClosingPage() {

  newPage();

  centerText(
    "Thank You",
    70,
    FONT.hero,
    COLORS.primary
  );

  paragraph(

    `This report was generated automatically by DevDNA using publicly available GitHub repository information .

The generated insights should be treated as guidance rather than absolute evaluation. Continue building meaningful software projects, experimenting with new technologies and contributing to open source.`,

    PAGE.margin,

    PAGE.contentWidth

  );

  moveY(15);

  centerText(
    "Keep Building. Keep Learning.",
    pdf.cursorY,
    FONT.h2,
    COLORS.secondary
  );

}

/* ==========================================================
                    MAIN EXPORT FUNCTION
========================================================== */

export default function exportPdf(data, username) {

  initPDF(data, username);

  drawCoverPage();

  drawExecutiveDashboard();

  drawRoleAnalysis();

  drawLanguageAnalysis();

  drawLearningRoadmap();

  drawDeveloperAssessment();

  drawFinalRecommendations();

  drawReportSummary();

  drawClosingPage();

  return pdf.doc.save(
    `${username}_DevDNA_Report.pdf`
  );

}
